### ISSUE TITLE
Consider Support for Accessing Azure Keyvault Secrets from Configuration

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-azure#222]
It would be a nice feature to be able to inject azure keyvault secrets into application configuration.

Perhaps something like this:

```yml
datasources:
  postgres:
    url: jdbc:postgresql://localhost:5432/db
    username: username
    password: ${AZUREKV("secret-id")}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
```

Where `secret-id` would be the ID of the secret in Azure Keyvault.

The reserved function `AZUREKV()` within the curly braces would allow for Micronaut to parse it accordingly and retrieve secret.

I'm open to other syntax and formatting, but just wanted to throw this out as an option.  Obviously we would need other information to identify the appropriate key vault as well.
